name: quotle
description: A Quote guessing game.
publish_to: 'none'
version: 1.1.3


environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  confetti: ^0.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  http: ^0.13.6
  intl: any
  logging: ^1.1.1
  share_plus: 4.0.2
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - .env